### ISSUE TITLE
run_tests problem

### ISSUE THREAD

**Issue by thesourcerer8** [pfalcon/ScratchABlock#28]
run_tests currently specifies #!/bin/sh in the first line, but unfortunately it actually requires bash and some distributions lately switched to other shells for /bin/sh which aren't compatible to run_tests, so please change it to #!/bin/bash
When running with /bin/sh which is a symlink to /bin/dash I get the following output:
./run_tests
./run_tests: 8: [: unexpected operator
./run_tests: 67: [: unexpected operator
./run_tests: 70: [: unexpected operator
./run_tests: 73: [: unexpected operator
./run_tests: 76: [: unexpected operator
TESTS PASSED

**Comment by pfalcon** [comment]
Strange that Travis didn't catch this, it's supposed to run on a clean Ubuntu system? Anyway, fixed in bc40d02e145cc215ab66fc3ca3ecdfb0c7cb05c7 , thanks for report.

**Comment by thesourcerer8** [comment]
Thanks!
