### ISSUE TITLE
Follow Van Emmerik terminology on function annotations

### ISSUE THREAD

**Issue by pfalcon** [pfalcon/ScratchABlock#5]
Van Emmerik thesis, section 3.4.1 "Call Related Terminology", page 77 thesis/page 137 pdf numeration.

The biggest change will be renaming collect_args and friends to collect_params.

**Comment by pfalcon** [comment]
This was implemented with refactors yesterday and today.

**Comment by pfalcon** [comment]
Btw, @mewmew, feel free to join the initiative to use Van Emmerik's terminology as close as possible, to avoid confusion.

**Comment by mewmew** [comment]
> Btw, @mewmew, feel free to join the initiative to use Van Emmerik's terminology as close as possible, to avoid confusion.

I would like to improve my knowledge and use of vocabulary in these areas, and finally allow myself time to read through Van Emmerik's paper. Have had it on my todo list for too long :)
